name = "app"
version = "1.0.0"
dev-dependencies = { lustre_dev_tools = ">= 1.6.5 and < 2.0.0" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = "5.0.3"
modem = ">= 2.0.1 and < 3.0.0"
wisp = ">= 1.6.0 and < 2.0.0"
